const MASTER_ENDPOINT=process.env.TRHONCAL_MASTER_ENDPOINT||'https://script.google.com/macros/s/AKfycbxq6OxUnMWH004OKyspo7eAbI0GvJvwwDgSnfffSzn9amtKzOWqaDmtWUnrk52rz7U8/exec';
const VALID=new Set(['verified','verified-initial','approved','published']);
function esc(v=''){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function safe(v=''){try{const u=new URL(String(v));return /^https?:$/.test(u.protocol)?u.toString():'';}catch(_){return '';}}
function visible(o){if(!o)return false;if(o.showWeb===false||String(o.showWeb||'').toLowerCase()==='no')return false;const e=o.expirationDate||o.expiresAt||o.fechaExpiracionWeb||'';if(/^\d{4}-\d{2}-\d{2}$/.test(String(e))&&new Date(`${e}T23:59:59`)<new Date())return false;return true;}
async function master(){const sep=MASTER_ENDPOINT.includes('?')?'&':'?';const c=new AbortController(),t=setTimeout(()=>c.abort(),10000);try{const r=await fetch(`${MASTER_ENDPOINT}${sep}_ts=${Date.now()}`,{cache:'no-store',redirect:'follow',signal:c.signal,headers:{'User-Agent':'TrhoncalTravel-DestinationsV2/1.0'}});if(!r.ok)throw new Error('master');return await r.json();}finally{clearTimeout(t);}}
export default async function handler(req,res){
 if(req.method!=='GET'){res.setHeader('Allow','GET');return res.status(405).send('Method not allowed');}
 let p;try{p=await master();}catch(_){return res.status(503).send('No pudimos cargar los destinos.');}
 const offers=(Array.isArray(p.offers)?p.offers:[]).filter(visible),destinations=(Array.isArray(p.destinations)?p.destinations:[]).filter(d=>d&&d.slug&&VALID.has(d.status));
 const count=new Map();offers.forEach(o=>count.set(o.destinationId,(count.get(o.destinationId)||0)+1));
 const groups=new Map();destinations.forEach(d=>{const state=d.state||'Otros destinos';if(!groups.has(state))groups.set(state,[]);groups.get(state).push(d);});
 const sections=[...groups.entries()].sort((a,b)=>a[0].localeCompare(b[0],'es')).map(([state,items])=>`<section class="dv2-state"><div class="dv2-state-head"><h2>${esc(state)}</h2><span>${items.length} destino${items.length===1?'':'s'}</span></div><div class="dv2-grid">${items.sort((a,b)=>a.name.localeCompare(b.name,'es')).map(d=>{const n=count.get(d.id)||0,img=safe(d.mainImage);return `<article class="dv2-card"><a class="dv2-image" href="/destino-v2/${encodeURIComponent(d.slug)}">${img?`<img src="${esc(img)}" alt="${esc(d.imageAlt||d.name)}" loading="lazy">`:'<div>Descubre este destino</div>'}</a><div class="dv2-body"><span class="eyebrow">${esc(d.country||'México')}</span><h3>${esc(d.name)}</h3><p>${esc(d.summary||'')}</p><div class="dv2-foot"><strong>${n?n+' viaje'+(n===1?'':'s')+' disponible'+(n===1?'':'s'):'Viaje a tu medida'}</strong><a href="/destino-v2/${encodeURIComponent(d.slug)}">${n?'Ver viajes':'Conocer y cotizar'} →</a></div></div></article>`;}).join('')}</div></section>`).join('');
 res.setHeader('Content-Type','text/html; charset=utf-8');res.setHeader('X-Robots-Tag','noindex,nofollow');res.setHeader('Cache-Control','public, s-maxage=60, stale-while-revalidate=180');
 return res.status(200).send(`<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Todos los destinos | Trhoncal Travel V2</title><meta name="robots" content="noindex,nofollow"><link rel="stylesheet" href="/assets/css/styles.css"><link rel="stylesheet" href="/assets/css/brand-v2.css"><style>body{background:#f7f4ed;color:#063f53}.dv2-main{padding:42px 0 70px}.dv2-hero{display:grid;grid-template-columns:1fr .8fr;gap:28px;align-items:end;margin-bottom:38px}.dv2-hero h1{font-size:clamp(42px,6vw,72px);line-height:.98;margin:6px 0}.dv2-hero p{color:#60747a;line-height:1.65}.dv2-state{margin-top:42px}.dv2-state-head{display:flex;justify-content:space-between;align-items:end;border-bottom:1px solid rgba(6,63,83,.14);padding-bottom:12px;margin-bottom:18px}.dv2-state-head h2{font-size:32px;margin:0}.dv2-state-head span{font-size:12px;font-weight:900;color:#8d6928}.dv2-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:18px}.dv2-card{background:#fff;border:1px solid rgba(216,175,88,.3);border-radius:24px;overflow:hidden;display:flex;flex-direction:column}.dv2-image{display:block;aspect-ratio:16/9;background:#0a5064;color:#fff;text-decoration:none}.dv2-image img{width:100%;height:100%;object-fit:cover;display:block}.dv2-image div{height:100%;display:grid;place-items:center}.dv2-body{padding:19px;display:flex;flex-direction:column;flex:1}.dv2-body h3{font-size:27px;margin:6px 0 8px}.dv2-body p{color:#60747a;line-height:1.55;margin:0 0 18px}.dv2-foot{margin-top:auto;padding-top:14px;border-top:1px solid rgba(6,63,83,.1);display:flex;justify-content:space-between;gap:12px;align-items:end}.dv2-foot strong{font-size:12px}.dv2-foot a{font-weight:900;color:#063f53;text-decoration:none;text-align:right}@media(max-width:900px){.dv2-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.dv2-hero{grid-template-columns:1fr}}@media(max-width:620px){.dv2-grid{grid-template-columns:1fr}.dv2-state-head{align-items:flex-start;flex-direction:column;gap:5px}.dv2-foot{align-items:flex-start;flex-direction:column}}</style></head><body><header class="site-header"><div class="container header-inner"><a class="brand" href="/"><img class="brand-logo" src="/assets/images/trhoncal-travel-logo.svg" alt="Trhoncal Travel"></a><nav class="nav"><a href="/destinos-v2">Destinos</a><a href="/cuando-viajar/">Cuándo viajar</a><a href="/ofertas-v2">Ofertas</a></nav><a class="btn btn-outline" href="https://wa.me/523329335952">WhatsApp</a></div></header><main class="dv2-main"><div class="container"><div class="dv2-hero"><div><span class="eyebrow">Encuentra por dónde empezar</span><h1>¿A dónde quieres ir?</h1></div><p>Explora destinos por estado. Cuando exista un viaje publicado verás cuántas opciones hay; si todavía no hay una promoción, podemos armarla a tu medida.</p></div>${sections}</div></main></body></html>`);
}
