const MASTER_ENDPOINT = process.env.TRHONCAL_MASTER_ENDPOINT ||
  'https://script.google.com/macros/s/AKfycbxq6OxUnMWH004OKyspo7eAbI0GvJvwwDgSnfffSzn9amtKzOWqaDmtWUnrk52rz7U8/exec';

function esc(v=''){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function scriptJson(value){return JSON.stringify(value).replace(/</g,'\\u003c').replace(/\u2028/g,'\\u2028').replace(/\u2029/g,'\\u2029');}
function iso(v=''){return /^\d{4}-\d{2}-\d{2}$/.test(String(v))?String(v):'';}
function todayIso(){const d=new Date(),off=d.getTimezoneOffset();return new Date(d.getTime()-off*60000).toISOString().slice(0,10);}
async function loadMaster(){const sep=MASTER_ENDPOINT.includes('?')?'&':'?';const c=new AbortController(),t=setTimeout(()=>c.abort(),10000);try{const r=await fetch(`${MASTER_ENDPOINT}${sep}_ts=${Date.now()}`,{cache:'no-store',redirect:'follow',signal:c.signal,headers:{'User-Agent':'TrhoncalTravel-QuoteV2/2.0'}});if(!r.ok)throw new Error('master');return await r.json();}finally{clearTimeout(t);}}
function occupancyAdults(text=''){const m=String(text).match(/(\d+)\s*adult/i);return m?Number(m[1]):2;}

export default async function handler(req,res){
  if(req.method!=='GET'){res.setHeader('Allow','GET');return res.status(405).send('Method not allowed');}
  const requestedSlug=String(req.query.slug||'').trim().toLowerCase();
  let payload={destinations:[],offers:[]};try{payload=await loadMaster();}catch(_){}
  const destinations=Array.isArray(payload.destinations)?payload.destinations:[],offers=Array.isArray(payload.offers)?payload.offers:[];
  const offerId=String(req.query.oferta||'').trim(),offer=offers.find(o=>o&&o.id===offerId)||null;
  let destination=destinations.find(d=>d&&d.slug===requestedSlug)||null;if(!destination&&offer)destination=destinations.find(d=>d&&d.id===offer.destinationId)||null;
  const destinationName=offer?.leadDestinationVerified||destination?.name||String(req.query.destino||'').trim()||'Ayúdame a elegir';
  const destinationSlug=destination?.slug||requestedSlug||'';
  let start=iso(req.query.salida||offer?.travelStart||''),end=iso(req.query.regreso||offer?.travelEnd||'');if(start&&end&&end<start)end='';
  const plan=String(req.query.plan||offer?.plan||'Recomiéndame'),occasion=String(req.query.ocasion||offer?.occasionId||'');
  const adults=Math.min(20,Math.max(1,Number(req.query.adultos)||occupancyAdults(offer?.occupancy||''))),minors=Math.min(8,Math.max(0,Number(req.query.menores)||0));
  const title=offer?`Tu viaje a ${destinationName}`:`Arma tu viaje a ${destinationName}`,offerLabel=offer?.hotel||offer?.title||'',promoUrl=offer?.publicPromoUrl||offer?.sharePromoUrl||'';
  const backUrl=destinationSlug?`/destino-v2/${encodeURIComponent(destinationSlug)}${offer?'#opciones':''}`:'/destinos-v2/';
  const minDate=todayIso();
  const metaScript=scriptJson({destinationSlug,offerId,occasion,promoUrl,cta:String(req.query.cta||'quote_v2')});
  res.setHeader('Content-Type','text/html; charset=utf-8');res.setHeader('X-Robots-Tag','noindex,nofollow');res.setHeader('Cache-Control','no-store');
  return res.status(200).send(`<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} | Trhoncal Travel</title><meta name="robots" content="noindex,nofollow"><link rel="icon" type="image/svg+xml" href="/assets/images/trhoncal-travel-logo.svg"><link rel="stylesheet" href="/assets/css/styles.css"><link rel="stylesheet" href="/assets/css/brand-v2.css"><link rel="stylesheet" href="/assets/css/v2-polish.css"><style>body{background:#f7f4ed;color:#063f53}.qv2-wrap{width:min(980px,calc(100% - 28px));margin:28px auto 80px}.qv2-card{background:#fff;border:1px solid rgba(6,63,83,.1);border-radius:28px;box-shadow:0 18px 58px rgba(6,63,83,.08);overflow:hidden}.qv2-head{padding:30px 34px 24px;background:linear-gradient(135deg,#fff,#fbf5e7)}.qv2-head h1{font-size:clamp(34px,5vw,58px);line-height:1;margin:8px 0 12px}.qv2-context{display:flex;flex-wrap:wrap;gap:8px;margin-top:14px}.qv2-context span{background:#f7eed8;border-radius:999px;padding:8px 11px;font-weight:800;font-size:12px}.qv2-form{padding:28px 34px 34px}.qv2-grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}.qv2-field{display:flex;flex-direction:column;gap:7px;font-weight:800}.qv2-field span{font-size:13px}.qv2-field input,.qv2-field select{min-height:48px;border:1px solid #ccd8da;border-radius:13px;padding:0 13px;font:inherit;color:#063f53;background:#fff}.qv2-field input[readonly]{background:#f6f1e7}.qv2-family{margin:22px 0;padding:20px;border-radius:20px;background:#f8f5ed;border:1px solid #ead9b2}.qv2-family h2{font-size:24px;margin:0 0 6px}.qv2-family p{margin:0 0 14px;color:#607279}.qv2-ages{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-top:12px}.qv2-consent{display:flex;gap:10px;align-items:flex-start;margin:18px 0;font-size:13px}.qv2-actions{display:flex;align-items:center;gap:14px;flex-wrap:wrap}.qv2-actions button{border:0;border-radius:999px;background:#063f53;color:#fff;padding:15px 22px;font:inherit;font-weight:900;cursor:pointer}.qv2-actions button:disabled{opacity:.65;cursor:wait}.qv2-status{font-weight:800;font-size:13px}.qv2-status.err{color:#9e2e22}.qv2-status.ok{color:#15713c}@media(max-width:700px){.qv2-wrap{margin-top:18px}.qv2-head,.qv2-form{padding-left:20px;padding-right:20px}.qv2-grid{grid-template-columns:1fr}.qv2-ages{grid-template-columns:1fr 1fr}.qv2-actions button{width:100%}}</style></head><body class="qv2-page">
<header class="site-header"><div class="container header-inner"><a class="brand" href="/"><img class="brand-logo" src="/assets/images/trhoncal-travel-logo.svg" alt="Trhoncal Travel"></a><nav class="nav"><a href="/destinos-v2/">Destinos</a><a href="/cuando-viajar/">Cuándo viajar</a><a href="/ofertas-v2/">Ofertas</a></nav><a class="btn btn-outline" href="https://wa.me/523329335952">WhatsApp</a></div></header>
<nav class="v2-context-nav" aria-label="Navegación del formulario"><div class="container v2-context-nav-inner"><a href="${esc(backUrl)}">← ${destinationSlug?`Volver a viajes para ${esc(destinationName)}`:'Volver a destinos'}</a><div class="v2-context-group"><a href="/destinos-v2/">Todos los destinos</a><a href="/ofertas-v2/">Ver todas las ofertas →</a></div></div></nav>
<main class="qv2-wrap"><section class="qv2-card"><div class="qv2-head"><span class="eyebrow">Trhoncal Travel · solicitud de viaje</span><h1>${esc(title)}</h1><p>${offer?'Ya elegiste una opción. Completa quiénes viajan y tus datos para confirmar disponibilidad y condiciones.':'Cuéntanos cómo viajan y armamos una opción para ti.'}</p><div class="qv2-context"><span>Destino: ${esc(destinationName)}</span>${offerLabel?`<span translate="no" class="notranslate">${esc(offerLabel)}</span>`:''}${start?`<span>${esc(start)}${end?` → ${esc(end)}`:''}</span>`:''}</div></div>
<form id="qv2" class="qv2-form"><div class="qv2-grid"><label class="qv2-field"><span>Nombre *</span><input name="nombre" autocomplete="given-name" required></label><label class="qv2-field"><span>Apellido</span><input name="apellido" autocomplete="family-name"></label><label class="qv2-field"><span>WhatsApp *</span><input name="whatsapp" type="tel" inputmode="tel" autocomplete="tel" required></label><label class="qv2-field"><span>Ciudad de salida *</span><input name="ciudadSalida" placeholder="Ej. Guadalajara" required></label><label class="qv2-field"><span>Destino</span><input name="destino" value="${esc(destinationName)}" readonly></label><label class="qv2-field"><span>Hospedaje *</span><select name="hospedaje" required><option${plan==='Todo incluido'?' selected':''}>Todo incluido</option><option${plan==='Sin todo incluido'?' selected':''}>Sin todo incluido</option><option${plan==='Recomiéndame'?' selected':''}>Recomiéndame</option></select></label><label class="qv2-field"><span>Fecha aproximada de salida *</span><input name="fechaSalida" type="date" min="${minDate}" value="${esc(start)}" required></label><label class="qv2-field"><span>Fecha aproximada de regreso</span><input name="fechaRegreso" type="date" min="${esc(start||minDate)}" value="${esc(end)}"></label></div>
<section class="qv2-family"><h2>¿Quiénes viajan?</h2><p>Las edades importan porque pueden cambiar el precio de hotel y paquete.</p><div class="qv2-grid"><label class="qv2-field"><span>Adultos *</span><input name="adultos" type="number" min="1" max="20" value="${adults}" required></label><label class="qv2-field"><span>Menores / juniors</span><input name="menores" type="number" min="0" max="8" value="${minors}"></label></div><div id="ages" class="qv2-ages"></div></section>
<label class="qv2-consent"><input name="consentimiento" type="checkbox" required><span><b>Autorizo el contacto.</b> Acepto que Trhoncal Travel me contacte para dar seguimiento a esta solicitud.</span></label><input name="website" tabindex="-1" autocomplete="off" aria-hidden="true" style="position:absolute;left:-9999px"><div class="qv2-actions"><button id="send" type="submit">Solicitar cotización →</button><span id="status" class="qv2-status" role="status" aria-live="polite"></span></div></form></section>
<section class="v2-explore-more"><div class="v2-explore-card"><div><span class="eyebrow">¿Quieres comparar antes?</span><h2>Puedes salir sin perderte</h2><p>Revisa destinos u ofertas y vuelve cuando quieras.</p></div><div class="v2-explore-actions"><a class="btn btn-outline" href="/destinos-v2/">Todos los destinos</a><a class="btn btn-primary" href="/ofertas-v2/">Ver ofertas →</a></div></div></section></main>
<script>const form=document.getElementById('qv2'),ages=document.getElementById('ages'),status=document.getElementById('status'),send=document.getElementById('send');const meta=${metaScript};function renderAges(){const n=Math.max(0,Math.min(8,Number(form.menores.value)||0));const old=[...ages.querySelectorAll('input')].map(x=>x.value);ages.innerHTML='';for(let i=0;i<n;i++){const l=document.createElement('label');l.className='qv2-field';l.innerHTML='<span>Edad menor / junior '+(i+1)+' *</span><input aria-label="Edad menor o junior '+(i+1)+'" type="number" min="0" max="17" required value="'+(old[i]||'')+'">';ages.appendChild(l);}}function syncDates(){const s=form.fechaSalida.value,r=form.fechaRegreso;const min=s||${scriptJson(minDate)};r.min=min;if(r.value&&s&&r.value<s)r.setCustomValidity('La fecha de regreso no puede ser anterior a la salida.');else r.setCustomValidity('');}form.menores.addEventListener('input',renderAges);form.fechaSalida.addEventListener('change',syncDates);form.fechaRegreso.addEventListener('change',syncDates);renderAges();syncDates();form.addEventListener('submit',async e=>{e.preventDefault();syncDates();if(!form.reportValidity())return;const adults=Number(form.adultos.value)||0,minors=Number(form.menores.value)||0,ageValues=[...ages.querySelectorAll('input')].map(x=>String(x.value).trim());if(ageValues.length!==minors||ageValues.some(x=>x==='')){status.textContent='Indica la edad de cada menor o junior.';status.className='qv2-status err';return;}const total=adults+minors;const body={nombre:form.nombre.value,apellido:form.apellido.value,whatsapp:form.whatsapp.value,destino:form.destino.value,ciudadSalida:form.ciudadSalida.value,fechaSalida:form.fechaSalida.value,fechaRegreso:form.fechaRegreso.value,personas:String(total),adultos:String(adults),menores:String(minors),edadesMenores:ageValues.join(','),hospedaje:form.hospedaje.value,consentimiento:form.consentimiento.checked,website:form.website.value,origen:'formulario_v2',urlOrigen:location.href,slugDestino:meta.destinationSlug,ocasionId:meta.occasion,ofertaId:meta.offerId,promoUrl:meta.promoUrl,ctaOrigen:meta.cta};send.disabled=true;send.textContent='Enviando…';status.textContent='Registrando tu solicitud…';status.className='qv2-status';try{const r=await fetch('/api/lead',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await r.json().catch(()=>({}));if(!r.ok||data.ok!==true)throw new Error(data.error||'No pudimos registrar la solicitud.');status.textContent='¡Listo! '+(data.leadId?'Folio '+data.leadId:'Solicitud recibida.');status.className='qv2-status ok';send.textContent='Solicitud recibida ✓';}catch(err){status.textContent=err.message||'No pudimos registrar la solicitud.';status.className='qv2-status err';send.disabled=false;send.textContent='Intentar de nuevo →';}});</script></body></html>`);
}
